---
  - name: palo-fw-change-password
    hosts: localhost
    gather_facts: no
    vars_files:
      - "variables/variables.yml"
    pre_tasks:
      - include_tasks: _get_aws_info.yml


      - name: "Update device Provider ip_address"
        set_fact:
          palo_fw_connection_creds:
            username: "{{ palo_fw_default_username }}"
            password: "{{ palo_fw_password }}"
            ip_address: "{{ palo_fw_ec2_details.instances[0].public_ip_address }}"

      - name: debug
        ansible.builtin.debug:
          msg: "{{ palo_fw_connection_creds }}"

    tasks:
      - name: "Wait to become available (can take up to 30 minutes for a new VM)"
        uri:
          url: "https://{{ palo_fw_connection_creds.ip_address }}"
          method: GET
          status_code: 200
          validate_certs: no
        register: result
        until: result.status == 200
        retries: 90
        delay: 20

      - name: "Set admin password"
        paloaltonetworks.panos.panos_admpwd:
          ip_address: "{{ palo_fw_connection_creds.ip_address }}"
          username: "{{ palo_fw_connection_creds.username }}"
          key_filename: "../.secrets/palo-fw-workshop-{{ ec2_name_tag }}"
          newpassword: "{{ palo_fw_connection_creds.password }}"
        register: result
        until: result is not failed
        retries: 10
        delay: 30